export enum OwnerType {
  VEHICLE = 'VEHICLE',
  DRIVER = 'DRIVER',
}

export enum DocumentType {
  VEHICLE_LICENSE = 'VEHICLE_LICENSE',
  REGISTRATION = 'REGISTRATION',
  INSURANCE = 'INSURANCE',
  COMPREHENSIVE_INSURANCE = 'COMPREHENSIVE_INSURANCE',
  INSPECTION = 'INSPECTION',
  EXHAUST_EMISSION = 'EXHAUST_EMISSION',
  MUNICIPALITY_PERMIT = 'MUNICIPALITY_PERMIT',
  TAXI_PLATE_PERMIT = 'TAXI_PLATE_PERMIT',
  DRIVER_LICENSE = 'DRIVER_LICENSE',
  SRC_CERTIFICATE = 'SRC_CERTIFICATE',
  PSYCHOTECHNIC_CERTIFICATE = 'PSYCHOTECHNIC_CERTIFICATE',
  CRIMINAL_RECORD = 'CRIMINAL_RECORD',
  ID_CARD = 'ID_CARD',
  CONTRACT = 'CONTRACT',
}

export enum DocumentStatus {
  VALID = 'VALID',
  EXPIRING = 'EXPIRING',
  EXPIRED = 'EXPIRED',
}

export const VEHICLE_DOCUMENT_TYPES: DocumentType[] = [
  DocumentType.VEHICLE_LICENSE,
  DocumentType.REGISTRATION,
  DocumentType.INSURANCE,
  DocumentType.COMPREHENSIVE_INSURANCE,
  DocumentType.INSPECTION,
  DocumentType.EXHAUST_EMISSION,
  DocumentType.MUNICIPALITY_PERMIT,
  DocumentType.TAXI_PLATE_PERMIT,
];

export const DRIVER_DOCUMENT_TYPES: DocumentType[] = [
  DocumentType.DRIVER_LICENSE,
  DocumentType.SRC_CERTIFICATE,
  DocumentType.PSYCHOTECHNIC_CERTIFICATE,
  DocumentType.CRIMINAL_RECORD,
  DocumentType.ID_CARD,
  DocumentType.CONTRACT,
];

export const DOCUMENT_EXPIRING_THRESHOLD_DAYS = 30;

export enum DocumentSortField {
  CREATED_AT = 'createdAt',
  EXPIRY_DATE = 'expiryDate',
  TITLE = 'title',
  TYPE = 'type',
}
